deckeditor/urls.py
from django.urls import path
from . import views

app_name = 'deckeditor'

urlpatterns = [
    path('', views.CardListView.as_view(), name='list'),
    path('<int:pk>/', views.CardDetailView.as_view(), name='detail'),
]

tcg/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('deckeditor.urls')),
    path('admin/', admin.site.urls),
]

deckeditor/models.py
from django.db import models

class Deck (models.Model):
    name = models.CharField('Deck Name', max_length = 100)
    format = models.CharField('Format', max_length = 50)
    main_cards = models.CharField('Main Deck', max_length = 10000)
    side_cards = models.CharField('Sideboard', max_length = 10000)
    commander = models.CharField('Commander', max_length = 50)


class Card (models.Model):
    oracle_id = models.CharField('Oracle ID', max_length = 36)
    back_name = models.CharField('Back', blank=True, max_length = 100)
    name = models.CharField('Name', max_length = 100)
    mana_cost = models.CharField('Mana Cost', blank=True, max_length = 50)
    cmc = models.CharField('MV', max_length = 2)
    colors = models.CharField('Colors', blank=True, max_length = 15)
    color_identity = models.CharField('Identity', blank=True, max_length = 15)
    art_crop = models.CharField('Art', blank=True, max_length = 200)
    type_line = models.CharField('Type', max_length = 100)
    set = models.CharField('Set', max_length = 5)
    set_name = models.CharField('Set', max_length = 50)
    keywords = models.CharField('Keywords', max_length = 250)
    legalities = models.CharField('Legalities', max_length = 250)
    oracle_text = models.CharField('Oracle', blank=True, max_length = 1000)
    flavor_text = models.CharField('Flavor', blank=True, max_length = 1000)
    artist = models.CharField('Artist', blank=True, max_length = 50)
    power = models.CharField('Power', blank=True, max_length = 3)
    toughness = models.CharField('Toughness', blank=True, max_length = 3)
    rarity = models.CharField('Rarity', max_length = 1)

    def __str__ (self):
        cardstring = f"{self.name}. {self.mana_cost}, {self.type_line}, {self.rarity}, self.set"
        return cardstring

    def general_id(self):
        card = Card.objects.get(name=self.name)
        return card.id

deckeditor/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Card

class CardListView(ListView):
    model = Card
    context_object_name = 'cards'
    template_name = 'list.html'
    paginate_by = 150
    
    def get_queryset(self):
        qs = super().get_queryset()
        searchbox = self.request.GET.get('searchbox')
        format = self.request.GET.get('format')
        if (searchbox):
            filtered = qs.filter(name__icontains=searchbox).filter(legalities__icontains=format)
            return filtered
        else:
            return qs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        name = self.request.GET.get('searchbox')
        format = self.request.GET.get('format')
        if (name):
            context['title'] = f'Search Results for {name} in {format}:'
        else:
            context['title'] = 'List of Magic: the Gathering cards'
        self.request.session.set_expiry(0)
        visits = self.request.session.get('visits', 0)
        self.request.session['visits'] = visits+1
        context['visits'] = visits
        return context

class CardDetailView(DetailView):
    model = Card
    context_object_name = 'card'
    template_name = 'detail.html'

deckeditor/templates/detail.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta charset="UTF-8">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<title> Details for {{ card.name }}</title>
</head>
<body>
<p align="center"><h1>Card Detail</h1></p>
<p>{{ card.name }}&nbsp;&nbsp;&nbsp;&nbsp;{{card.mana_cost}}<br>
<img src="{{card.art_crop}}" alt="Art by {{card.artist}}"><br>
{{ card.type_line }}&nbsp;&nbsp;&nbsp;&nbsp;:{{card.set}}<br>
{{ card.oracle_text }}<br>
{{card.flavor_text}}<br>
{{ card.power }}/{{ card.toughness }}</p>
<p>Rarity: {{ card.rarity }}; {{ card.set_name }}</p>
<h6>Projeto de estudo em Django.</h6>
</body>
</html>

deckeditor/templates/index.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta charset="UTF-8">
<title>Aprendendo Javascript</title>
</head>
<body>
<main>

<h1>{{ title }}:</h1>
<p>Este é o primeiro parágrafo, ele só tem eta linha mesmo.</p>
<p>Já este é o segundo parágrafo, até um pouco mais curto.</p>
<p>E este é o terceiro, que embora seja tão informativo quanto os anteriores, ao menos tem um pouco mais de corpo, chegando a pelo menos duas ou três linhas quando exibido na página. Além disso, o terceiro parágrafo é o único com mais de uma frase e também o último da série.</p>

<h2>Projeto de estudo em Django.</h2>

</main>
</body>
</html>

deckeditor/templates/list.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'liststylesheet.css' %}">
<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta charset="UTF-8">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<title>{{ title }}</title>
</head>
<body>
<p align="center"><h1>{{ title }}:</h1></p>
{% if cards %}
<form action="">
{% csrf_token %}
<fieldset>
<label for 'searchbox'>Card Search: </label><input type="text" id="searchbox" name="searchbox">&nbsp;
<input type="submit" value="Pesquisar"><br>
<label for="standard">Standard</label><input type="radio" id="standard" checked="checked" name="format" value="Standard">&nbsp;
<label for="pioneer">Pioneer</label><input type="radio" id="pioneer" name="format" value="Pioneer">&nbsp;
<label for="modern">Modern</label><input type="radio" id="modern" name="format" value="Modern">&nbsp;
<label for="legacy">Legacy</label><input type="radio" id="legacy" name="format" value="Legacy">&nbsp;
<label for="commander">Commander</label><input type="radio" id="commander" name="format" value="Commander">&nbsp;
<br>
</fieldset>
</form>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last</a>
        {% endif %}
    </span>
</div>
<table>
<tr><th>Card Name</th><th>Cost</th><th>Type</th><th>P/T/L</th><th>Rarity</th></tr>
{% for card in cards %}
<tr><td>
<a href="{% url 'deckeditor:detail' card.id %}">{{card.name}}</a>
{% if card.back_name %}
 (<a href="{% url 'deckeditor:detail' card.id|add:"1"%}">{{card.back_name}}</a>)
{% endif %}
</td><td>{{card.mana_cost}}</td><td>{{card.type_line}}</td><td>{{card.power}}/{{card.toughness}}</td><td>{{card.rarity}}</td></tr>
{% endfor %}
</table>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% else %}
<p align="center">No cards found with given search terms.</p>
{% endif %}
<h6>Você visualizou esta página {{ visits }} vezes.</h6>
</body>
</html>